name: Self Hosted Runner Test

on:
  push:

jobs:
  build:
    runs-on: [self-hosted, naranjanl]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show system info
        run: uname -a
      - name: Show system info
        run: date
