name: Self Hosted Runner Test

on:
  push:

jobs:
  build:
    runs-on: [self-hosted, naranjanl]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show system info
        run: uname -a
      - name: Show system info
        run: ping6 2001:bc8:1d90:1ab:dc00:ff:fe09:ddd7
